// Central permission key constants for the new module/submodule/action permission
// system (fed by GET /users/getuserdetail/{userId} -> data.permissions.sections).
// Keys are exact, case-sensitive strings matching the backend's module_key /
// submodule_key / action_key values. Never key off module_name / action_name.

export const PERMISSION_MODULES = {
  KANBAN_WORKSPACE: "KANBAN_WORKSPACE",
  KANBAN_WORKFLOW: "KANBAN_WORKFLOW",
  KANBAN_CARD: "KANBAN_CARD",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  ENTITY_MANAGEMENT: "ENTITY_MANAGEMENT",
  VESSEL_MANAGEMENT: "VESSEL_MANAGEMENT",
  OPERATIONS_CONFIGURATIONS: "OPERATIONS_CONFIGURATIONS",
  TIME_OBJECT_MANAGEMENT: "TIME_OBJECT_MANAGEMENT",
  CHECKLIST_MANAGEMENT: "CHECKLIST_MANAGEMENT",
  LAUNCH_HIRE_MANAGEMENT: "LAUNCH_HIRE_MANAGEMENT",
  HOTEL_MANAGEMENT: "HOTEL_MANAGEMENT",
  HOSPITAL_MANAGEMENT: "HOSPITAL_MANAGEMENT",
  TRANSPORT_MANAGEMENT: "TRANSPORT_MANAGEMENT",
  ON_STATION: "ON_STATION",
  TASK_CARD: "TASK_CARD",
  OUTLOOK: "OUTLOOK",
  BUSINESS_RULES: "BUSINESS_RULES",
  CARD_MANAGEMENT: "CARD_MANAGEMENT",
  THIRD_PARTY_SERVICE: "THIRD_PARTY_SERVICE",
  MATERIAL_MANAGEMENT: "MATERIAL_MANAGEMENT",
  SETTINGS: "SETTINGS",
};

export const PERMISSION_SUBMODULES = {
  CREW_IMMIGRATION: "CREW_IMMIGRATION",
  OPERATORS: "OPERATORS",
  USERS: "USERS",
};

export const PERMISSION_ACTIONS = {
  VIEW: "VIEW",
  CREATE: "CREATE",
  ADD: "ADD",
  EDIT: "EDIT",
  DELETE: "DELETE",
  UPLOAD: "UPLOAD",
  ARCHIVE: "ARCHIVE",
  DISABLE: "DISABLE",
  PERMISSION: "PERMISSION",
  TOGGLE_STATUS: "TOGGLE_STATUS",
  CREATE_WORKSPACE: "CREATE_WORKSPACE",
  REQUEST_LAUNCH_HIRE: "REQUEST_LAUNCH_HIRE",
};
