import { useState } from "react";
import PropTypes from "prop-types";
import CustomModal from "../../../../../../components/CustomModal";
import { Modal } from "react-bootstrap";

const ReportsCardView = ({ reportsList, cardColor, onViewReport, onDownloadReport }) => {
  const [previewReport, setPreviewReport] = useState(null);

  const formatDate = (dateString) => {
    if (!dateString) return "";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const formatFileSize = (sizeInKB) => {
    if (sizeInKB < 1024) {
      return `${sizeInKB} KB`;
    }
    return `${(sizeInKB / 1024).toFixed(2)} MB`;
  };

  const getStatusClass = (status) => {
    const statusMap = {
      Generated: "status-generated",
      Pending: "status-pending",
      Failed: "status-failed",
      "In Progress": "status-in-progress",
    };
    return statusMap[status] || "";
  };

  const handlePreview = (report) => {
    console.log("Opening preview for report:", report);
    setPreviewReport(report);
  };

  const handleClosePreview = () => {
    setPreviewReport(null);
  };

  const handleViewReport = (report) => {
    // Always open preview modal first
    handlePreview(report);
    // Optionally call parent callback if provided
    if (onViewReport) {
      onViewReport(report);
    }
  };

  const handleDownloadReport = (report) => {
    if (onDownloadReport) {
      onDownloadReport(report);
    } else {
      console.log("Download report:", report);
    }
  };

  return (
    <>
      <div className="reports-card-view-section">
        <div className="reports-card-view-header">
          <h3 className="reports-card-view-title">
            <span className="reports-card-view-title-bar"></span>
            REPORTS
          </h3>
        </div>
        <div className="reports-card-grid">
          {reportsList.map((report) => (
            <div key={report.id} className="reports-card" style={{ "--card-color": cardColor }}>
              <div className="reports-card-header">
                <div className="reports-card-name">{report.reportName || ""}</div>
                <div className={`reports-card-status ${getStatusClass(report.status)}`}>
                  {report.status || ""}
                </div>
              </div>
              <div className="reports-card-body">
                <div className="reports-card-info-item">
                  <span className="reports-card-label">Type:</span>
                  <span className="reports-card-value">{report.reportType || "N/A"}</span>
                </div>
                <div className="reports-card-info-item">
                  <span className="reports-card-label">Generated Date:</span>
                  <span className="reports-card-value">{formatDate(report.generatedDate)}</span>
                </div>
                <div className="reports-card-info-item">
                  <span className="reports-card-label">Generated By:</span>
                  <span className="reports-card-value">{report.generatedBy || "N/A"}</span>
                </div>
                <div className="reports-card-info-item">
                  <span className="reports-card-label">File Size:</span>
                  <span className="reports-card-value">{formatFileSize(report.fileSize)}</span>
                </div>
              </div>
              <div className="reports-card-actions">
                <button
                  type="button"
                  className="reports-card-action-btn preview"
                  onClick={() => handlePreview(report)}
                  title="Preview"
                  style={{ "--card-color": cardColor }}
                >
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                      d="M8 3C4.5 3 1.73 5.11 0 8C1.73 10.89 4.5 13 8 13C11.5 13 14.27 10.89 16 8C14.27 5.11 11.5 3 8 3ZM8 11C6.34 11 5 9.66 5 8C5 6.34 6.34 5 8 5C9.66 5 11 6.34 11 8C11 9.66 9.66 11 8 11ZM8 6.5C7.17 6.5 6.5 7.17 6.5 8C6.5 8.83 7.17 9.5 8 9.5C8.83 9.5 9.5 8.83 9.5 8C9.5 7.17 8.83 6.5 8 6.5Z"
                      fill="currentColor"
                    />
                  </svg>
                  <span>Preview</span>
                </button>
                <button
                  type="button"
                  className="reports-card-action-btn download"
                  onClick={() => handleDownloadReport(report)}
                  title="Download"
                  style={{ "--card-color": cardColor }}
                >
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                      d="M8 11V2M8 11L5 8M8 11L11 8M2 13H14"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                  <span>Download</span>
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Preview Modal using CustomModal */}
      <CustomModal
        className="reports-preview-modal"
        dialgName="modal-dialog modal-dialog-centered modal-lg"
        show={!!previewReport}
        closeModal={handleClosePreview}
        header={
          <div className="reports-preview-modal-header">
            <h3 className="reports-preview-modal-title">
              <span className="reports-preview-modal-title-bar" style={{ backgroundColor: cardColor }}></span>
              PREVIEW: {previewReport?.reportName || ""}
            </h3>
          </div>
        }
        body={
          <div className="reports-preview-content">
            {previewReport && (
              <>
                <div className="reports-preview-info">
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">Report Name:</span>
                    <span className="reports-preview-value">{previewReport.reportName}</span>
                  </div>
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">Report Type:</span>
                    <span className="reports-preview-value">{previewReport.reportType}</span>
                  </div>
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">Generated Date:</span>
                    <span className="reports-preview-value">{formatDate(previewReport.generatedDate)}</span>
                  </div>
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">Generated By:</span>
                    <span className="reports-preview-value">{previewReport.generatedBy}</span>
                  </div>
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">Status:</span>
                    <span className={`reports-preview-value ${getStatusClass(previewReport.status)}`}>
                      {previewReport.status}
                    </span>
                  </div>
                  <div className="reports-preview-info-row">
                    <span className="reports-preview-label">File Size:</span>
                    <span className="reports-preview-value">{formatFileSize(previewReport.fileSize)}</span>
                  </div>
                </div>
                <div className="reports-preview-placeholder">
                  <div className="reports-preview-placeholder-icon">
                    <svg width="64" height="64" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path
                        d="M14 2H6C5.46957 2 4.96086 2.21071 4.58579 2.58579C4.21071 2.96086 4 3.46957 4 4V20C4 20.5304 4.21071 21.0391 4.58579 21.4142C4.96086 21.7893 5.46957 22 6 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V8L14 2Z"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <path
                        d="M14 2V8H20"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <path
                        d="M16 13H8"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <path
                        d="M16 17H8"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <path
                        d="M10 9H9H8"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                  <p className="reports-preview-placeholder-text">Report Preview</p>
                  <p className="reports-preview-placeholder-subtext">
                    Click download to view the full report
                  </p>
                </div>
              </>
            )}
          </div>
        }
        footer={
          <Modal.Footer className="reports-preview-modal-footer">
            <button
              type="button"
              className="reports-preview-modal-btn secondary"
              onClick={handleClosePreview}
            >
              Close
            </button>
            <button
              type="button"
              className="reports-preview-modal-btn primary"
              onClick={() => {
                if (previewReport) {
                  handleDownloadReport(previewReport);
                  handleClosePreview();
                }
              }}
              style={{ backgroundColor: cardColor }}
            >
              Download
            </button>
          </Modal.Footer>
        }
        createModal={true}
        bodyClassname="reports-preview-modal-body"
      />
    </>
  );
};

ReportsCardView.propTypes = {
  reportsList: PropTypes.array.isRequired,
  cardColor: PropTypes.string,
  onViewReport: PropTypes.func,
  onDownloadReport: PropTypes.func,
};

export default ReportsCardView;

