import { useEffect } from "react";
import PropTypes from "prop-types";

// Generate dummy reports data
const generateDummyReports = () => {
  const reportTypes = ["Financial Report", "Performance Report", "Analytics Report", "Summary Report", "Detailed Report"];
  const statuses = ["Generated", "Pending", "Failed", "In Progress"];
  const generatedBy = ["John Doe", "Jane Smith", "Mike Johnson", "Sarah Williams", "David Brown"];

  const dummyReports = [];
  for (let i = 1; i <= 20; i++) {
    const generatedDate = new Date();
    generatedDate.setDate(generatedDate.getDate() - Math.floor(Math.random() * 90));

    dummyReports.push({
      id: i,
      reportName: `Report_${String(1000 + i).padStart(4, '0')}`,
      reportType: reportTypes[Math.floor(Math.random() * reportTypes.length)],
      generatedDate: generatedDate.toISOString().split('T')[0],
      generatedBy: generatedBy[Math.floor(Math.random() * generatedBy.length)],
      status: statuses[Math.floor(Math.random() * statuses.length)],
      fileSize: Math.floor(Math.random() * 5000 + 100), // KB
    });
  }
  return dummyReports;
};

const ReportsList = ({ formValues, handleChange, cardColor }) => {
  const reportsList = formValues.reportsList || [];

  // Initialize with dummy data on mount if empty
  useEffect(() => {
    if (!formValues.reportsList || formValues.reportsList.length === 0) {
      const dummyData = generateDummyReports();
      const syntheticEvent = { target: { value: dummyData } };
      handleChange("reportsList")(syntheticEvent);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Only run once on mount

  const displayReportsList = reportsList.length > 0 ? reportsList : generateDummyReports();

  const formatDate = (dateString) => {
    if (!dateString) return "";
    const date = new Date(dateString);
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  };

  const formatFileSize = (sizeInKB) => {
    if (sizeInKB < 1024) {
      return `${sizeInKB} KB`;
    }
    return `${(sizeInKB / 1024).toFixed(2)} MB`;
  };

  const getStatusClass = (status) => {
    const statusMap = {
      Generated: "status-generated",
      Pending: "status-pending",
      Failed: "status-failed",
      "In Progress": "status-in-progress",
    };
    return statusMap[status] || "";
  };

  const handleViewReport = (report) => {
    console.log("View report:", report);
    // TODO: Implement view functionality
  };

  const handleDownloadReport = (report) => {
    console.log("Download report:", report);
    // TODO: Implement download functionality
  };

  return (
    <div className="cardform-left-full reports-content-wrapper" style={{ "--card-color": cardColor }}>
      <div className="reports-list-header">
        <h3 className="reports-list-title">
          <span className="reports-list-title-bar"></span>
          REPORTS LIST
        </h3>
      </div>
      <div className="table-wrapper table-responsive reports-table-container">
        <table className="table table-striped reports-table" style={{ "--card-color": cardColor }}>
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Report Type</th>
              <th>Generated Date</th>
              <th>Generated By</th>
              <th>Status</th>
              <th>File Size</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {displayReportsList.map((report) => (
              <tr key={report.id}>
                <td>
                  <div className="reports-table-cell">{report.reportName || ""}</div>
                </td>
                <td>
                  <div className="reports-table-cell">{report.reportType || ""}</div>
                </td>
                <td>
                  <div className="reports-table-cell">{formatDate(report.generatedDate)}</div>
                </td>
                <td>
                  <div className="reports-table-cell">{report.generatedBy || ""}</div>
                </td>
                <td>
                  <div className={`reports-table-cell ${getStatusClass(report.status)}`}>
                    {report.status || ""}
                  </div>
                </td>
                <td>
                  <div className="reports-table-cell">{formatFileSize(report.fileSize)}</div>
                </td>
                <td>
                  <div className="reports-table-cell reports-actions">
                    {/* <button
                      type="button"
                      className="reports-action-btn view"
                      onClick={() => handleViewReport(report)}
                      title="View"
                      style={{ "--card-color": cardColor }}
                    >
                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                          d="M8 3C4.5 3 1.73 5.11 0 8C1.73 10.89 4.5 13 8 13C11.5 13 14.27 10.89 16 8C14.27 5.11 11.5 3 8 3ZM8 11C6.34 11 5 9.66 5 8C5 6.34 6.34 5 8 5C9.66 5 11 6.34 11 8C11 9.66 9.66 11 8 11ZM8 6.5C7.17 6.5 6.5 7.17 6.5 8C6.5 8.83 7.17 9.5 8 9.5C8.83 9.5 9.5 8.83 9.5 8C9.5 7.17 8.83 6.5 8 6.5Z"
                          fill="currentColor"
                        />
                      </svg>
                    </button> */}
                    <button
                      type="button"
                      className="reports-action-btn download"
                      onClick={() => handleDownloadReport(report)}
                      title="Download"
                      style={{ "--card-color": cardColor }}
                    >
                      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                          d="M8 11V2M8 11L5 8M8 11L11 8M2 13H14"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

ReportsList.propTypes = {
  formValues: PropTypes.object.isRequired,
  handleChange: PropTypes.func.isRequired,
  cardColor: PropTypes.string,
};

export default ReportsList;

